version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: next_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teresol
      MYSQL_USER: teresol_admin
      MYSQL_PASSWORD: teresol123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./teresol.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - appnet

  web:
    build: .
    container_name: next_app
    restart: always
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: "mysql://teresol_admin:teresol123@db:3306/teresol"
    depends_on:
      - db
    volumes:
      - ./public/uploads:/app/public/uploads   # âœ… mount the whole public/uploads folder
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge
